version: "3.8"
services:
  dcs-tarefaninja:
    image: postgres:16.1-alpine
    container_name: dcs-tarefaninja
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tarefaninja
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
